const assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
class Element{constructor(){this.children=[];this.textContent='';}append(...rows){this.children.push(...rows)}replaceChildren(...rows){this.children=rows}addEventListener(){}get text(){return this.textContent+this.children.map(e=>e.text).join('')}}
const nodes={},document={getElementById:id=>nodes[id]??=new Element(),createElement:()=>new Element(),querySelector:()=>new Element()};const context={document,Date,Number};vm.createContext(context);vm.runInContext(fs.readFileSync(__dirname+'/pulse-view.js','utf8'),context);const V=context.PulseView;
V.renderAccount({equity:'1100',cash:'123.45'},{armed:true,nav:[{equity:1000}]});assert.equal(nodes['pulse-equity'].textContent,'$1,100.00');assert.equal(nodes['pulse-cash'].textContent,'$123.45');assert.equal(nodes['pulse-change'].textContent,'+10.00%');
V.renderAccount({equity:1100,cash:123},{armed:true,pausedReason:'Temporary network failure'});assert.equal(nodes['pulse-mode'].textContent,'자동 운용 켜짐');assert(nodes['pulse-updated'].textContent.includes('확인 대기'));
V.renderAccount({equity:1100,cash:123},{});assert.equal(nodes['pulse-change'].textContent,'—');
V.renderPositions([{symbol:'AAA',market_value:'50',unrealized_plpc:'-.2'},{symbol:'BBB',market_value:'100',unrealized_plpc:'.1'}]);assert(nodes['pulse-positions'].children[0].text.includes('BBB'));assert(nodes['pulse-positions'].children[1].text.includes('-20.00%'));
V.renderOrders([{symbol:'CCC',side:'buy',status:'accepted',filled_qty:'0',filled_avg_price:null}]);assert(nodes['pulse-orders'].text.includes('접수'));assert(!nodes['pulse-orders'].text.includes('체결 완료'));assert(nodes['pulse-orders'].text.includes('—'));
V.clear();assert.equal(nodes['pulse-equity'].textContent,'—');assert(!nodes['pulse-positions'].text.includes('BBB'));assert(!nodes['pulse-orders'].text.includes('CCC'));
console.log('PASS: broker values, no invented baseline return, actual positions sorting, unfilled orders stay unfilled, account reset clears prior records');
